name: "Check Spelling"
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          incremental_files_only: true
